server:
  port: 8066
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_jing_msc?characterEncoding=utf-8&useUnicode=true&rewriteBatchedStatements=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Fullsee@123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml